package com.buzz.mysite.model;

import java.time.LocalDateTime;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.Id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account_no
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_date
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.updated_id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private String updatedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.updated_date
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.Id
     *
     * @return the value of sys_user.Id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.Id
     *
     * @param id the value for sys_user.Id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.account_no
     *
     * @return the value of sys_user.account_no
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.account_no
     *
     * @param accountNo the value for sys_user.account_no
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_id
     *
     * @return the value of sys_user.create_id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_id
     *
     * @param createId the value for sys_user.create_id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_date
     *
     * @return the value of sys_user.create_date
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_date
     *
     * @param createDate the value for sys_user.create_date
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.updated_id
     *
     * @return the value of sys_user.updated_id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public String getUpdatedId() {
        return updatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.updated_id
     *
     * @param updatedId the value for sys_user.updated_id
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setUpdatedId(String updatedId) {
        this.updatedId = updatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.updated_date
     *
     * @return the value of sys_user.updated_date
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.updated_date
     *
     * @param updatedDate the value for sys_user.updated_date
     *
     * @mbggenerated Fri Jan 25 15:51:44 CST 2019
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}