spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.105.95.251:3306/buzz
    username: buzzuser
    password: 96mhLv0SvKKosdaM
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
profiles:
  security:
    user:
      name: user
      password: 123
  thymeleaf:
    suffix: .html
    cache: false
    prefix: classpath:/templates/
    enabled: true
  mvc:
    static-path-pattern: /static/**
redis:
    host: 192.168.1.123
    password: 123
mybatis:
  check-config-location: true
  typeAliasesPackage: com.buzz.mysite.model
  mapperLocations: classpath:mapper/*.xml

