spring:
  security:
    user:
      name: user
      password: 123
  thymeleaf:
    suffix: .html
    cache: false
    prefix: classpath:/templates/
    enabled: true
  mvc:
    static-path-pattern: /static/**
  test:
     name: 123
     value: 456
redis:
    host: 192.168.1.123
    password: 123
mybatis:
  check-config-location: true
